# Generated by Django 2.0.2 on 2018-05-12 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('attr', models.TextField()),
                ('background', models.TextField()),
                ('talent', models.TextField()),
                ('skill', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('intro', models.TextField()),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
                ('detail', models.TextField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dota2_data.Heros')),
            ],
        ),
    ]
