# Generated by Django 2.0.2 on 2018-05-13 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dota2_data', '0003_auto_20180512_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='hero',
        ),
        migrations.AlterField(
            model_name='heros',
            name='img',
            field=models.ImageField(blank=True, upload_to='dota2_data/static/dota2_data/img'),
        ),
        migrations.AlterField(
            model_name='heros',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dota2_data.Skills'),
        ),
        migrations.AlterField(
            model_name='items',
            name='logo',
            field=models.ImageField(blank=True, upload_to='dota2_data/static/dota2_data/img'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='logo',
            field=models.ImageField(blank=True, upload_to='dota2_data/static/dota2_data/img'),
        ),
    ]
