# Generated by Django 2.0.2 on 2018-05-13 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dota2_data', '0004_auto_20180513_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heros',
            name='skill',
        ),
        migrations.AddField(
            model_name='skills',
            name='heros',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='dota2_data.Heros'),
            preserve_default=False,
        ),
    ]
